apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'mikes-vpc:ec2.aws.crossplane.io/VPC:nethopper/mike-vpc'
    crossplane.io/external-name: vpc-0cc45ae39729d023b
  name: mike-vpc
spec:
  forProvider:
    region: us-west-2
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
    - key: Environment
      value: Dev
    - key: Owner
      value: Mike
    - key: Name
      value: mike-vpc
    instanceTenancy: default
  providerConfigRef:
    name: awsconfig
