apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: tfconfig
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
  - filename: aws-creds.ini
    source: Secret
    secretRef:
      namespace: nethopper
      name: aws-creds
      key: creds
#   - filename: git-credentials
#     source: Secret
#     secretRef:
#       namespace: nethopper
#       name: git-creds
#       key: creds
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
      provider "aws" {
        shared_credentials_file = "aws-creds.ini"
      }

      // Modules _must_ use remote state. The provider does not persist state.
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-default"
          namespace         = "nethopper"
          in_cluster_config = true
        }
      }

