apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: test-vpc
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 192.170.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
    - key: Environment
      value: Dev
    - key: Owner
      value: Mike
    - key: Name
      value: test-vpc
    instanceTenancy: default
  providerConfigRef:
    name: awsconfig
