apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: xplane-demo-aws-vpc
spec:
  forProvider:
    region: us-east-2
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
    - key: Environment
      value: Dev
    - key: Owner
      value: Nethopper
    - key: Name
      value: xplane-demo-aws-vpc
    instanceTenancy: default
  providerConfigRef:
    name: awsconfig
