apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: gke-gcp
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/infra-gitops.git//demo/users/chris/terraform/gke-gcp
# NOTE: Dont' define variables that you don't use, because this causes TF warning that could complicate Crossplane status
    vars:
#     - key: region
#       value: us-central1
    - key: project_id
      value: test-dd662
    # varFiles:
    # - source: SecretKey
    #   secretKeyRef:
    #     namespace: default
    #     name: vpc-azure-tfvars
    #     key: terraformtfvars
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-gke-gcp
  providerConfigRef:
    name: gcpconf
