apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: AWS
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-03-11T16:03:32-04:00'
    nethopper.io/generator-version: 6.0.0-alpha.8+001
  name: awscreds
  namespace: default
spec:
  encryptedData:
    awscredssdk: >-
      AgAqcshNSg8YLofXauRxffVJwViJ8IP7dkm9eP/tCya44E/l7a7HjdE/1mrXfGrbK+of5jIcbM4oAKiArhLn/oBXdt4DknBKQVY/LdQvwyNpwcwAKXPCgTTSS7o5Yus08NCDryHNYxD7I7Xkyof0SaKh/EjH0Kgmmjpul/un7CqDiRTg0fqEVLiI9okrvPqdVcVvVovCu/eprGuSeftwfCRNTCQcyUfYaZz1gE2CmnRKIgGwbKFmtbfD7fdlLJj2C9D/fv95rIn4TqSTfS4g5BMhONjVQ9tecy55l0rNFwS0XkL46iFw82jD1fyqiVJ4zjoIqdWBFEnHw8GAz9qX2l1MhWScO7QVbXiVi1RBOe8afzkZtCZetwW2+uZbWsoJq80sLzwqsSh+ilPd12pWWAxx+XFaDrlQh30AM9qv4jAZApPzCXVVI21qdMpGEoGykxdPttP+inPAokt8t7Cx1SFytE7CBVuXWkXuSIJbCjVmvo/rbDa8CFIRo7UOtxkiUu9TSdCOEeXjgic1inIbdUV5FY90HJGd/nUmDsB5Yih4U1/Tnkd5poamIvbcYkoVYa0B3SJxy1Z7eEei+SS4J+xwb65Lc1ulXeAeF+tkasjCoN+O+59HJltBKfVN30HCxPrNDEqkkQSZoxTA0U6FedbatCGwen2vrsVUgfmPt2w94pzed894vnuDPofGZbf1jedDCE8zCFgx+88KFlb/IO54XknaDvP1EIAnxbc2lmDV3+2PCDaUXQbFurmzw1KrnfusNebH3ulm0F+CzpmcAgPLLMLz/TNBV/EKWehi69a5UcFsUjAc4you92K69U0ESNH7xbEF+MR/CESoVTaETBNyQvtFfY7L0XKZn+s=
  template:
    metadata:
      annotations: *ref_0
      name: awscreds
    type: Opaque


