apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/generated-at: '2023-08-02T18:50:57-04:00'
    nethopper.io/generator-version: 4.6.1
  name: awscreds
  namespace: default
spec:
  encryptedData:
    awscreds: >-
      AgCjrLY2JmiEnFPUIYlELpiKm+gHZd0iu/dWFqm75U6dnMrolurRBeD6tEMppIsMBDjH5v4xgfSSDlypigUb5ZDJcrR/PXUk2qMJKYVZxtu7wJbYO4VgUOx6NTj/8ZewnNmG7uuAYuAWA+IHcSz2n1fglmfqIa8FALTEE+Ya25o9ACzZfjBgA0PSobtw1Xce8laZe0Z6c7LwtamZn9T/wgbY2un5PFzSP8Iqf61NIZhpSO4tQIWGmxUY9T2puvajaU72qY/ROskaNnR4ne+8ZDcXLkgXSU2WLq2D5FxMdDin/hhw8matRSdVHgbH4+sHietIeCqSmTR1nN8G9ckcrAi+7YaEiB/9f775Jps6vclWsTtnzo6mCOQ3bz0/BXQwwLsET5ycnleRNUIW2yIplMUxm4U/T3upVxFtL0kc7QQSn2RQ3PN5Jq6e2fQ1gAFg7ynna1KSaQTWcpVbuUzR9sDrEWmG34fXxHxkd7zfQU6387cwj1tDGD4Gbdj0agE/maVFTYBCofNjBygYrd296xcDLLI/3wU7MsS4iWOtyhegRLQyUHkIghHdMvcl3puGOheEXcneYeCczTSc17ECP36xdQsTkwit48Hr5HOMxH68PKoFXPEZ/zrSs/nkSrds86FLvNaH9DRSZLm1T0iDGKRmLlrtuWAt0STvLIsqf12LWkXVg8NFaL7Sc8Ls/VJ7I4it4VpNfSQ7Vid44xucsNNAZe/2OzRoF8MwkZn42GRHqp8HTV6NWUmBYBF6uShHAXainpXER9BxdzmdVEaID/KPu3uZ1YAIOzWhFheU3FKaulKVoBMGyZaftGldrrV/ml0Gh0wGqontXPnAA7vGcgf8QZcdOg==
  template:
    metadata:
      annotations: *ref_0
      name: awscreds
    type: Opaque
