apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/generated-at: '2023-08-02T18:06:21-04:00'
    nethopper.io/generator-version: 4.6.1
  name: awscred2
  namespace: default
spec:
  encryptedData:
    awscreds: >-
      AgAJi2JXXbwWjJnF5dVnGsMB8UM6AyKGe4RDxi+HmY4S4jngqRiRcH7/ieik9t3nS4eCem7iupL2ey+mQUDkGJCT7kiGiewyhTDUNI/Z2jfy66Yx08l5iBCJldT58GvtZ1CCLmbNnqc5Mcxvm/H42P58iiGlyYc0o43oeWUsjlqG40Udg0udgbwdgTnON2TFKLTc9Cu4MjLEaDDGMxCK3plPyu7XD9ebZnvjlwZvSfEMZQHNY+i4ITuOaF01OnTvjJIM7bsGsz1O03YAu7DeoGR7UaTi+vvIm4Kr8aH1OF/8bPXsbTCznuNzSiNgUBO9iILX6fajda5NOK3tlJTThDLnCHU/dZBUBCwt0ZcejHuPj/U/SCqt9AzftxNPWGU19oD18GiIxBNLha2Nryv5K028UPut7xKzk2o4hz0ReM9SFJfgdxrx/FHY6ifuqMjMWXeln8sH75icWTXMW8pbQ35ocxpDaY8Hx4UFUY00l7twbgCAT2MLBCOoVHKjwFPLnCoaq8EbOoQ3nfU2WARKL3NFLV0zQ+0rkUkBDLsG/Z1BikLy2f+H4NlmuJJUeq+ueV7PjMjAGJNsCE/+PhLq+FO8N8esHReRIkewOZtJ6RrKYK369kn14qR3MKYUTq9BYfn8FynnXbge+S12UrAxG5Irk2KcBizCTQQlWJR9eEzRo0AfaGAixG2RfKW7abAW+Yx8jp3mIhp01BQEeE+uhUdfnw57ZsqFusf07Xpgm+KsxNWfzQo0N2tcrQGvzBNzex5IYUGnUbzpHESUwhG47Ih+2GfsEE6ebayAxaHmQA/dfr5XZyWppLGeD0GiqY1hPlEs09HX2lphpareu5ledzeFsnIn1w==
  template:
    metadata:
      annotations: *ref_0
      name: awscred2
    type: Opaque
