apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/generated-at: '2023-08-16T12:41:21-04:00'
    nethopper.io/generator-version: 5.0.4
  name: awscreds
  namespace: default
spec:
  encryptedData:
    awscreds: >-
      AgDN/S4IqWDO+Jsz+MBEHlTyRkYRNJObmhshqtfMuTl4gWeOW4Q3kVppEtyfuByssfwj5h2ecOwtNHVLGHe+MPUw52MUfL+5qc7MfsxmA6nFvehHjuB5huaYD8Z8JYpnIonRYAXAh3jV4oLQlvZ1wktXsrsK3wW1xERhBJC6QqKUTPApvj802mXJaxtieyLUelW6dIumv52kipZkGXGvuG6rEIbu9oq8H0LyotsLTZ+t7Zh3tRqlcNaxAmB7LRk88VMPXEDdZFPkuMZU/N/F79yBDQ6w6A6aNrY8xNpqCF2DMq1QmJmopXeQgXGgc11Gs6fw3kmELy2Vcop39eYm28C3JAak/u5L3u+HrmCZpmvpVoBDu+B2lHk1aqINR+Qkk6G2eH9Z6+VBmP8HAr6Bw7IZr9/HsrvTDIOWvRLfD9aRwwohFD0XTdBTPUUafkM2c4sBz2nkoSBE6EY5Q5VrDtBsfNGqByU5l1Z3BxBtUQb7Zn4ryozQtIk0b4rbMKB+Dsdg9QdeLlVydHcokka2v4AK92AdURLqyvWsKngm5uRX/J6v77KCPqoZJSfY3Yo1C9rpdYLTpdMVM8JEWim4lyaaZp31WQrZldN1UsjSddVIAF0cV2N6ooMSCLy+YRvhw4X+pdgv+Ug8/vEo8btLcrI/lZaGhlcB/BJUzgqtEHhcH41FmoYNc5BfpHaYIwgvtdu9X9B7exXPyk+qUCRTe798HHgllpec02Bf9iTVSxwOCybKNDy9kuIA3v348Gb1zXum2AgmLsUfRZvqdUmvu/hp7qrIfMh6Ym4J3ZfWix2o27tvWCUXAGYxRyV1lpKB9ZFquU/KDGxMOx0d8EdDlFZB9Jwbxw==
  template:
    metadata:
      annotations: *ref_0
      name: awscreds
    type: Opaque
