apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/generated-at: '2023-07-12T09:50:56-04:00'
    nethopper.io/generator-version: 4.6.1
  name: awscreds
  namespace: default
spec:
  encryptedData:
    awscreds: >-
      AgDEH4yvwRKkThHV12+4lzz0YPAZQAtB6+RxM9b9L0HSm9MUMRZ/d03qzS11HmhlaS+taorxP0YLi89IJSfmlSsNK1dQ+wnss0f+igB3dnNPprd+mEK3e7L1apqlivWxlAMICN3a6E/BPyEUUfIhNGM8qOJerF3csj3ZR1DxRoFQMsFhE3j0FG9fO65634/NxaXTJ4azLgg0H5wwM7AcfhapDjmBxD/G2H26LiqLdm8AWwQIWr//Ge34Wk+g278UG070k5Y09Dq8r3cFPC2V/r2lKfLA2iejNP2ySNGJCLsLi1sN4fGj1Lu4nJB10O7tOeVKXWP3XwnaCoWGCpUTU68+Fpc0kpKqujYQ8eMLARG4bwtEbXHBiZ0jF+3w9geP1gtMkyF39lIbM1pUlot0zYD3lziBwP3QGg94HziPBwozr1aJIkUK8xHJmJh5a9/UgGLAUvQ2LjpjUxDdqW+dMX8YBCQ3zcbk0Oa6qHvSRlsoDkpMSbn0idK2Nu7rzhJLGHQVl7wDUbKuCF3oXzAo/l197Zi0Q2lgywK9GX3D4nybEstzVQoiwBjaWhy+ypjpVIUOnGt0PvsCGAinZ3ykbFNEtdtTNFX1GURKPZEFKQl/O2z+WJv1Yrs/Pk+u7hGdsYsIqvdfIwZVmHSeu4xgtM04CHdvcUqj5MuaT0v/1eGpUZlQDTD4eUjwkWuNmCldbnvf387SfCP5mbsVwSWuuayQWEFHOFZIItg2vyvz56/B2pnuebW3C8iFzZ02sZ+CZVpu+VX/842wMAHBAccSYIYZnsuq3XdEW3zUIxgoV12eEYVvmO2jD+dSJ0v4j94SO7giotJCP6Dl71YjZicJ7gzUYBNsLw==
  template:
    metadata:
      annotations: *ref_0
      name: awscreds
    type: Opaque


