apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: AWS
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-03-19T09:19:27-04:00'
    nethopper.io/generator-version: 6.0.0-alpha.9+001
  name: awscreds21
  namespace: default
spec:
  encryptedData:
    creds: >-
      AgBT6TO27Ec5yIaSeeAJVeQmRUxemEKGPW+o0P0MI2KZAe7lrcURa0IxzE5WmVY2N3h3cH8VNvvB+A1E3jlQhMtB4iGVkraW6nO4zU4pp5Us4hadryszZo+r+vGVJDzgAwJj/dULPOrgap3UbOuIFTDDY29TDxPrTdgkoTt8+B295uYD+LYjb3fsLQkxvwlLA45fJBSa6lcCbKc4N9v8F9nRNQhmbdI7uSMgvfeOEmBC8xULvc4kLyRvh6vkCoHNEaYkLFyNEANKiGQZQUUTQIOagdBozvBsKpxlcZ7TlL1M48Sk/S84euC2bbrWpYqxeSZmcyizFG9EJJSjWQv+pU45sQa5SONdKfHJ/NYwPpYaeWPYMzVeMqZhZdQeKzn0rtz4DrkiOQVufta2oZwJ+UEIGoeN8RKBQ+S6fdX8lYZePt2P7GA4511FlyRFu1Y3LLxxWPkFUqhV1Ta7YH5XSvL2IdrbALfqrwBCL5xfLnYyV0HJh2rbgNEQrmbJnms10EnqfhsHq2nK+NVrkdX5zZYJMgNPsf0clkj4Rc0oU6MsKdz91Vv4XwFm9wiIDn8/7cUtHhQrNGlzYIvjgvuRdiiHOIax/yLmCGwvGRBZmbs7dRDEmzjFO80weyOzNZvN2TJK7LAtktIil1Ay+bP9OEjd6DYBTUSbR08gacj2l6bmTwxzRH/dw+Q4aBrdHU2aYvk3uy13sJFbDDdBC5pciFrCQg9Q5buh/vGOweHNkZ9oWpk1/SFMN9hgYJbECbyZ3/bihSGaHWoDsVQjw7QucQEC/ktp4w==
  template:
    metadata:
      annotations: *ref_0
      name: awscreds21
    type: Opaque
