apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/generated-at: '2023-05-24T12:48:46-04:00'
    nethopper.io/generator-version: 4.5.1
  name: temp
  namespace: default
spec:
  encryptedData:
    temp: >-
      AgBM8Qfq6j48COCp2z0Sri0szy3xEDLOV6qsUVJ8Pm1zA8auPfCun4s/ob30+K2FDdsxhUL0ODUZ3wzSXzPDiqSJoIxt//O1AAZg42hPmkeQMopqVwLCKDWFH5MAkInd8WmH2gJGNFHibpNAP/V/rsMSyfHs96Cm97EUl08m+VRC5uPKiMz3qmxGvqNWAkIq78YxyFz7XavABxmyGb4T53JcX8wrGJSbLqNacJwvvO6YQ/BFhInLSx/sikHnceDMNGhN4Mi2PkVWegw068EpGmOWJDOQwRAI4hxXCGIIXj0wYMe3VEyMloMqzhb183LmIExx+iXhpKNvorTBiKOgP/4r7PPd8ZHruM43haGsxMAQyOOaAGkUvvWKcksNddurxnLiqNb4y2dXnaF4AYS/7d7bY6LwyeRtJtdLqaekShKfowx9ZfHz6plEj1R6Oef2r6FHUXe8Wdcd+kNhRpwM7VPoWYFQzLhv4X4uh88ciJAyx4ELFsiorNdSi/9UZIpycICH68tR1MrEUlmBZJiqRZFHx6yWxJvHBXJlSOvUkF8EYFzcCWylQaiiWEes4Zc2kpGGgBNM9tKzIhIvcP4406bfs8+zch28JljQszn9i3KfY6k9ibevXoc1nh0lnubszyqmJSKEv9aynnGN8BiXV9IVVdwHjDusJ0nQ5DH3DiW8lK5evm0OixfsNA8jbg1bz+6/o/d5
  template:
    metadata:
      annotations: *ref_0
      name: temp
    type: Opaque
