apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/generated-at: '2023-05-23T20:37:20-04:00'
    nethopper.io/generator-version: 4.5.1
  name: temp
  namespace: default
spec:
  encryptedData:
    temp: >-
      AgAaJ1ebOwPCuzQbavN7Dr1mm/SPCZBX175pATb4357CtwB9U7mX9+8YzJZCib8FZFt15MJagpilRtXSgquK6oCoQIbn0884XCdDnFKO8HHLR6twvTR108JcVRpOLfEZa99yb9bfPvega/B9gWMaC6/yu5ysIgsyScMJZpWCPYiWzEwKFgSKBP+jOTXY8e8dj0IxjpourfLLKETyfK469i+viJLJWKjGepKVKBO8qACdQF+bJmPugiFWxkn1aJC/hX27bhpIM60RnE7pwKOlTEd1gTL0uLtCXZETzqAjVAXUGfBMDbAeFc+uxHYESKAg343c/vojOglpy0C3EUgmTzVt2Mg5SgxOL4LERLlrotNY4l4FdWXb8Wg/8xQmvCUkCb8pigm/+21lPvqG/O6uMvXwQOymMlo5ODDYvb0yz5KIocutkz7hkF7Lgiinh1sgFgid2bFnSaqPza5tp1ctXvkkgMLEoezANCcDN0MjnO/jWLYayFUl77c4tdhM02rLxsWA/7nb4jjpDln5IHLKLXi2S6EqBu0xJm2OaQo75Mgqld8XRF1zgX8fFAOfGZv4zwZ9iHzCf+Yw8cBJsopwcdAfxPBuVMSMcWif3Bmjfqc7pbqQIjnfCdLW9osB/1x1ruywMY1KB1HcuJRrpoW6zgeoc7YXhg724buPu4R02cPKPvG2/CsNlNAKSOoBFt2qNgc+EcjP
  template:
    metadata:
      annotations: *ref_0
      name: temp
    type: Opaque
