apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: CUSTOM
    nethopper.io/iac-provider-name: temp
    nethopper.io/generated-at: '2024-03-18T19:00:53-04:00'
    nethopper.io/generator-version: 6.0.0-alpha.9+001
  name: tempabc
  namespace: default
spec:
  encryptedData:
    temp: >-
      AgAICe+7nsCKXNdNMD3G9s4GIZYC9BDGHwubX6vWXTeNyCX7YviQz0Rpf/8giY6mu/HfKn/933jb4t6CIcinr1T2gNouKg0Ef3tNFn8Tfx95RJbM+LDOk50PGHpSa56pDwEHckA9G+UEMV6aeGrsZwsKDm5lPLsGJrIk+nHZ9Q2+rDkZf1i+IKrQQRcNeYBaTQHIivJxSKasz+RVCJo3NjhX8PI05AFKtQw7tLQTQsFTkLqrfIaTdgreUkfmj+rQ4oy3olmv6gwnY8C+C56lQCNRR9QAgRamAfZ04bdhIt+5LThSkjA82nPm/WBAQUMlsSNLhIzJQDlrGDFhID3xdeEazGb2pcJFEF20+5Ve9IddhCYYP3Z2C+ZplkPC+o6ECX7TUXfZgg4PoJkrQl+kjTFQ+baOLHWPH9hZNBmqKYHOoochuheod6rU//5T6+xa6eGyb5B/LFyuwerfq+JmhiZiJL9WYB29At7pStxW24F4FrTsJoOqi1WmzKHXYArHTmGRAn3tuGab9F/fjvYCPDi9tvbTjLsnncpdjZB3spktOmCJ1JW7cyX3vt2T83j6W9ID96rM7i1+Vm+iHG186GN8UU8FzAU0koIWYFv2vMvUtuMLno1zzQa/OSQWGFMpkWIBVxLMl5HmpRze/cUsZ4ghbFdXi3M79Npj6dpAAqLq/DAS6ppRTSq47eLuXI5GUoz0ZcVM
  template:
    metadata:
      annotations: *ref_0
      name: tempabc
    type: Opaque
