apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/generated-at: '2024-02-21T13:45:04-05:00'
    nethopper.io/generator-version: 6.0.0-alpha.5+001
  name: temp
  namespace: default
spec:
  encryptedData:
    temp: >-
      AgAkouMqyGzFohz/XyBEWDQ/6cfUcigwNFmMlcJzv+NeIVoXCRBTTEPUC9dQ6P/+jAJFXRx/05pXrj0iKXvO6ixQXinxbDvV4Q4XJAz5tmprGCxIy+ddEJlLmX3Ir8adEv6KrCSfGQqfKeJ6UFekdyYx+sjzEdL+zq7UyGpCJOAfIEOTEZgJm/bgaPVUGNixB0QRZziCJWhCvcWPvt5PI8AE4BAyC5NCScTXjf6Ndm1e0gho0DyPY6+/xk/rIy/b39t4F8troYC9M+/vEDF0zcKty+58vVGcpSisPR9W9AGLI//HfSYL4UOHC20FNCmyWbTueSThyKaX5dNhtU59SUG4fWmR2+vFkfFR06uwfO77W2cPriI3kGX8HTMs9pipB5EhugcVPQx0e3dbG5ubgpU/+L7NWz1DWO8ihJ2Ul3YQZI1vDKQe58r3VfJNdxrWKFqnLJJ1o8LhxRkq1hfn0/WUO8jGWrWWeGxf+VF5EKQT8Aw+mh8uFDUSG1IBiGPbvTkuCyftmyQoOWANq3HKPVK8xwGsKN39iyPqdbxz4/dGQQvTzydtufmNvQrYYOFdVVBr1vKkgeFMLQbavX83lurTmCUv6p1Rch78Ug7//gI7cAL5c6tazSd6lmdZHo+Z8xThH90Gqd+jTUu59huPkJNLq8BOXnGhJA0IeV+UHCx2CC7NDWIdntdHMNzBzuQ146b98VD0
  template:
    metadata:
      annotations: *ref_0
      name: temp
    type: Opaque
