apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeKubernetesCluster
metadata:
  name: mikes-eks-cluster
  labels:
    cluster-owner: mike
spec:
  compositionRef:
    # Possible values cluster-google, cluster-azure, cluster-aws
    name: cluster-aws
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    # version: "1.20"
    # minNodeCount: 2
  writeConnectionSecretToRef:
    namespace: iacode
    name: cluster
