apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: AWS
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-06-10T16:29:03-04:00'
    nethopper.io/generator-version: 6.0.7-beta
  name: awscreds
  namespace: default
spec:
  encryptedData:
    creds: >-
      AgBEZ/JlgEE5/rvEo/M/3o91GNNpUH6oBD/xqtEKkubeL7uR+nObC8+6R24p/rSARePwks+q0ZfiB6nu/J/J5eT9rpN8U0jSp+WMnKrbqRWLFV2EejCDtd92Zh2EyNgm9f87v1gZbrc58/4DrEcDDGJ55eKlV2djy/MaLeepicQ1As96eKn67K8NOeUgUnit5aURMJ1uT+4UaklAfrHJhzvfuBvJVebMzrxypqLfg0pV55DGSlQNudpxXJ2gSDkUxLzqkl9tQu9B+lLIdemRD+C6B0xH3XSxDuvdl+0xlnnz9YFdnkgGmfBYI1pnQtFUJdWWH8B71ywLd0f0XoulgyVlqJJHryhesxA99osYI9msty+xRdnesjbTClMUtw8R831ZUUQxMv+zUEx+7YY3qJGaGdoLo6knHB0JQtAr322EGDHW2POeuCju1NTZr/YnYph4f5kUTpkicfYnP4jKuaS+TAuQ+NvVcNLCb7srCjRzeAugYyhYVeXFQdmJlDHDGafYBrJHWRhXqnaeigaMocdOgHzwBBu2Mz3C125YmGgf4YO7bVbE+lsXWdLz7PxOicikvffjEgmDTroZzYVcQfmcjrybtQ1qoqqxUfDTQOPrJ4uBcnrYZj+rr2tMkwdSwuWs0JI+KQE3dHnysQ/vJuAybg68t8RpWUkqVnDO1ApsTqQG6Hfv589uybkMWllWUFKJwaRJ1TXnkfLwTyHwknXSJJoZUpiW2TJDKj1juGNDZpbVlnUbVYvgF45X0dG0AefTa0wBSH3p7gzFwzk8KH8GHMpLRj2y4CwifYziyQJ7aVYR7cNWLsGEPD8vNQfVle/Wn60rsIPm1jmBQW/GkNpblNTVfD59H3PluBc=
  template:
    metadata:
      annotations: *ref_0
      name: awscreds
    type: Opaque


