apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/generated-at: '2024-06-07T13:32:38-04:00'
    nethopper.io/generator-version: 6.0.7-beta
  name: secret1
  namespace: default
spec:
  encryptedData:
    '1': >-
      AgAYbcjPZ+zAwnFHEBYs4+VwdJES6z1HFOfluqcAzuQOu/LzHSkJR2zVSL0/ul1MLHm97/HatKMeKkAAF3QYlDj86I/HrOqY6rnxct3Ijf5sMYJCnWYHooUoFo0+YDdPXSZHIXW/8KnsuqILA3snb60NK4BjTwurvHGFCjaZ7v3cWR30bqy5hguF3mdUIyNJWKonyUe0hMsjNCqcrvWpZqTeUoH5rDETAN0exBscFIMbs6prV/4elRg+vA3l6Ir6n2JR6haCFMBvBEs/vwuWpb6as7F/g5oUgw0hCBWAZ3tE7MFo85IFry2XyMtc329xtUyo02WemP9DCpiLD1m81tV76x1HtjctbSUXyGB8RR88fzLJ2U+Jmfb15f0eQdSWkJAejxKhwUJJZY/X8m0UXAfs0nkv+S433ZrVHNQ83qcMnbkl3j+UVY4A4YATigsfjKiwtDMpDRR4TUWzA5jaMIwtCXQw+cVuy+YkGny/iEVTotc4yyr4gWpUiRTpe2dIqD3ECHtkYlhswcm1kEAFJx9t7U+vDLg4iKBcZRnBNu6OnqEFzNcqXlG17+Ra45VQmg6j6B4Zfo7lE4J/frxbzJpswEI+AJeY4A687Pihn4NykBmD7ZSfcuI+F/F+f4cFfv+fWhZLkMMa5DqvFIwmPaDGPZZA+8K2nlQmrNwa7UP2eeDt637YbKSelXI+VV6Bkg6j
  template:
    metadata:
      annotations: *ref_0
      name: secret1
    type: Opaque


